# Generated by Django 3.2.5 on 2022-03-02 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0002_auto_20220217_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapsProd',
            fields=[
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productions.productions')),
                ('amount_of_caps', models.IntegerField()),
                ('conc_per_cap', models.FloatField()),
                ('conc_per_tab', models.FloatField()),
                ('amount_of_weighed_tabs', models.IntegerField()),
                ('mass_all_tabs', models.FloatField()),
                ('required_mass_powder', models.FloatField()),
                ('weighed_mass_powder', models.FloatField()),
                ('caps_size', models.FloatField(choices=[(1.37, '000'), (0.91, '00'), (0.78, '0'), (0.5, '1'), (0.37, '2'), (0.3, '3'), (0.21, '4'), (0.1, '5')])),
            ],
        ),
    ]
