# Generated by Django 3.2.5 on 2022-03-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps_prod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsprod',
            name='required_amount_of_tabs',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
