# Generated by Django 3.2.5 on 2022-03-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps_prod', '0002_capsprod_required_amount_of_tabs'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsprod',
            name='mass_required_volume',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capsprod',
            name='required_volume',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capsprod',
            name='tara_meas_cylinder',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
