# Generated by Django 3.2.5 on 2022-04-03 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps_prod', '0003_auto_20220312_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsprod',
            name='calc_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
