# Generated by Django 3.2.5 on 2022-04-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps_prod', '0004_capsprod_calc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsprod',
            name='mass_required_volume_incl_tara',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
