# Generated by Django 3.2.5 on 2022-04-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps_prod', '0005_capsprod_mass_required_volume_incl_tara'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsprod',
            name='conc_per_cap_actual',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capsprod',
            name='conc_powdermix_per_g_actual',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capsprod',
            name='conc_powdermix_per_g_target',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capsprod',
            name='conc_powdermix_per_ml_actual',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capsprod',
            name='conc_powdermix_per_ml_target',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
