# Generated by Django 3.2.5 on 2022-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps_prod', '0006_auto_20220407_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsprod',
            name='conc_powdermix_per_ml_actual',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='conc_powdermix_per_ml_target',
        ),
        migrations.AddField(
            model_name='capsprod',
            name='conc_powdermix_per_g_diff',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
