# Generated by Django 3.2.5 on 2022-04-07 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caps_prod', '0007_auto_20220407_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsprod',
            name='conc_per_cap_actual',
        ),
    ]
