# Generated by Django 3.2.5 on 2022-07-17 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caps_prod', '0008_remove_capsprod_conc_per_cap_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsprod',
            name='amount_of_caps',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='amount_of_weighed_tabs',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='calc_date',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='conc_per_cap',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='conc_per_tab',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='conc_powdermix_per_g_actual',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='conc_powdermix_per_g_diff',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='conc_powdermix_per_g_target',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='mass_all_tabs',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='required_amount_of_tabs',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='required_mass_powder',
        ),
        migrations.RemoveField(
            model_name='capsprod',
            name='weighed_mass_powder',
        ),
    ]
