# Generated by Django 3.2.5 on 2022-07-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps_prod', '0009_auto_20220717_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='capsprod',
            name='release_note',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
