# Generated by Django 3.2.5 on 2022-03-26 12:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0003_alter_productions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupposUniformity',
            fields=[
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productions.productions')),
                ('calc_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('mass_10_suppos', models.FloatField()),
                ('mass_max1', models.FloatField()),
                ('mass_max2', models.FloatField()),
                ('mass_max3', models.FloatField()),
                ('mass_min1', models.FloatField()),
                ('mass_min2', models.FloatField()),
                ('mass_min3', models.FloatField()),
                ('diff', models.FloatField()),
                ('diff_x2', models.FloatField()),
                ('mean', models.FloatField()),
                ('plus_1_diff', models.FloatField()),
                ('plus_2_diff', models.FloatField()),
                ('minus_1_diff', models.FloatField()),
                ('minus_2_diff', models.FloatField()),
                ('counter_above_1_diff', models.IntegerField()),
                ('counter_above_2_diff', models.IntegerField()),
                ('release_note', models.BooleanField()),
                ('uniformity_plot', models.ImageField(upload_to='')),
            ],
        ),
    ]
