# Generated by Django 3.2.5 on 2022-05-27 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0019_alter_ambvvalue_roa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ALTPrice',
            fields=[
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productions.productions')),
                ('substances_price', models.FloatField(null=True)),
            ],
        ),
    ]
