# Generated by Django 3.2.5 on 2022-05-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alt_price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='altprice',
            name='suppos_up_to_12',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
