# Generated by Django 3.2.5 on 2022-05-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alt_price', '0002_altprice_suppos_up_to_12'),
    ]

    operations = [
        migrations.AddField(
            model_name='altprice',
            name='suppos_other_12',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='altprice',
            name='suppos_up_to_12',
            field=models.IntegerField(default=1),
        ),
    ]
