# Generated by Django 3.2.5 on 2022-05-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alt_price', '0003_auto_20220527_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='altprice',
            name='amount_betmg',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='final_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='suppos_box_up_to_12',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='altprice',
            name='suppos_other_12',
            field=models.IntegerField(null=True),
        ),
    ]
