# Generated by Django 3.2.5 on 2022-07-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alt_price', '0004_auto_20220527_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='altprice',
            name='betmg_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='caps_mixing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='caps_other_25',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='caps_shell_25',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='caps_sieving',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='caps_up_to_25',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='manual_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='packaging_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='pulvis_100_ml',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='altprice',
            name='pulvis_50_ml',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='altprice',
            name='suppos_box_up_to_12',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='altprice',
            name='suppos_up_to_12',
            field=models.IntegerField(null=True),
        ),
    ]
