# Generated by Django 3.2.5 on 2022-03-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppos_prod', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supposdisplacementvalue',
            old_name='values',
            new_name='value',
        ),
    ]
