# Generated by Django 3.2.5 on 2022-04-02 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0003_alter_productions_options'),
        ('suppos_prod', '0002_rename_values_supposdisplacementvalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supposdisplacementvalue',
            name='substance',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='SupposProd',
            fields=[
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productions.productions')),
                ('amount_of_suppos', models.IntegerField()),
                ('conc_per_suppo', models.FloatField()),
                ('calibration_value', models.FloatField()),
                ('required_mass_active_substance', models.FloatField()),
                ('weighed_mass_active_substance', models.FloatField()),
                ('required_mass_witepsol', models.FloatField()),
                ('weighed_mass_witepsol', models.FloatField()),
                ('active_substance_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppos_prod.supposdisplacementvalue')),
            ],
        ),
    ]
