# Generated by Django 3.2.5 on 2022-04-08 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppos_prod', '0003_auto_20220402_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='supposprod',
            name='calc_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='supposprod',
            name='conc_suppomass_per_g_actual',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supposprod',
            name='conc_suppomass_per_g_diff',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supposprod',
            name='conc_suppomass_per_g_target',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supposprod',
            name='mass_suppomass_actual',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
