# Generated by Django 3.2.5 on 2022-05-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppos_prod', '0005_alter_supposprod_active_substance_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supposprod',
            name='active_substance_1',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='amount_of_suppos',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='calibration_value',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='conc_per_suppo',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='conc_suppomass_per_g_actual',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='conc_suppomass_per_g_diff',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='conc_suppomass_per_g_target',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='mass_suppomass_actual',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='required_mass_active_substance',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='required_mass_witepsol',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='weighed_mass_active_substance',
        ),
        migrations.RemoveField(
            model_name='supposprod',
            name='weighed_mass_witepsol',
        ),
        migrations.AddField(
            model_name='supposprod',
            name='actual_mass_bulk',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supposprod',
            name='actual_mass_bulk_incl_tara',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supposprod',
            name='calib_value_suppo_mould',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supposprod',
            name='diff_mass_bulk',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supposprod',
            name='tara_pouring_bowl',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supposprod',
            name='target_mass_bulk',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
