# Generated by Django 3.2.5 on 2022-05-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppos_prod', '0006_auto_20220525_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='supposprod',
            name='calculated_mass_bulk',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
