# Generated by Django 3.2.5 on 2022-05-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppos_prod', '0007_supposprod_calculated_mass_bulk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supposprod',
            old_name='diff_mass_bulk',
            new_name='diff_actual_mass_bulk',
        ),
        migrations.AddField(
            model_name='supposprod',
            name='diff_calculated_mass_bulk',
            field=models.FloatField(default=23),
            preserve_default=False,
        ),
    ]
