# Generated by Django 3.2.5 on 2022-05-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppos_prod', '0008_auto_20220525_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='supposprod',
            name='release_note',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
