# Generated by Django 3.2.5 on 2022-07-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppos_prod', '0009_supposprod_release_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupposDisplacementValue',
        ),
    ]
