# Generated by Django 3.2.5 on 2022-04-08 14:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productions', '0003_alter_productions_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupposMassBalance',
            fields=[
                ('calc_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('production', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productions.productions')),
                ('conc_per_suppo_actual', models.FloatField()),
                ('conc_per_suppo_diff', models.FloatField()),
                ('release_note', models.BooleanField()),
            ],
        ),
    ]
