# Generated by Django 3.2.5 on 2022-05-26 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppos_mass_balance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supposmassbalance',
            old_name='conc_per_suppo_actual',
            new_name='mass_balance_diff',
        ),
        migrations.RenameField(
            model_name='supposmassbalance',
            old_name='conc_per_suppo_diff',
            new_name='mass_balance_in_g',
        ),
    ]
