# Generated by Django 3.2.5 on 2022-01-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapsulesUniformityOfMassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_1_caps_empty', models.FloatField()),
                ('mass_20_caps_full', models.FloatField()),
                ('mass_max1', models.FloatField()),
                ('mass_min1', models.FloatField()),
            ],
        ),
    ]
