# Generated by Django 3.2.5 on 2022-01-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0002_capsulesuniformityofmassmodel_caps_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapsulesUniformityOfMassModel',
            new_name='CapsUnifM',
        ),
    ]
