# Generated by Django 3.2.5 on 2022-01-27 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0003_rename_capsulesuniformityofmassmodel_capsunifm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapsUnifM',
            new_name='Uniformity',
        ),
    ]
