# Generated by Django 3.2.5 on 2022-01-28 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0004_rename_capsunifm_uniformity'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformity',
            name='calc_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
