# Generated by Django 3.2.5 on 2022-02-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0005_uniformity_calc_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformity',
            name='mass_max2',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='mass_max3',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='mass_min2',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='mass_min3',
            field=models.FloatField(default=3.0),
            preserve_default=False,
        ),
    ]
