# Generated by Django 3.2.5 on 2022-02-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0007_auto_20220207_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformity',
            name='mass_1_caps_empty',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_20_caps_full',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_max1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_max2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_max3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_min1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_min2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_min3',
            field=models.FloatField(),
        ),
    ]
