# Generated by Django 3.2.5 on 2022-02-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0008_auto_20220215_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformity',
            name='mean',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
