# Generated by Django 3.2.5 on 2022-02-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0009_uniformity_mean'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformity',
            name='counter_above_1_diff',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='counter_above_2_diff',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='diff',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='diff_x2',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='minus_1_diff',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='minus_2_diff',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='plus_1_diff',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='plus_2_diff',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='release_note',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uniformity',
            name='uniformity_plot',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
