# Generated by Django 3.2.5 on 2022-02-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0010_auto_20220216_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformity',
            name='uniformity_plot',
            field=models.ImageField(upload_to=''),
        ),
    ]
