# Generated by Django 3.2.5 on 2022-02-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0011_alter_uniformity_uniformity_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformity',
            name='counter_above_1_diff',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='counter_above_2_diff',
            field=models.IntegerField(),
        ),
    ]
