# Generated by Django 3.2.5 on 2022-02-17 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
        ('capsules', '0012_auto_20220217_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniformity',
            name='production',
            field=models.ForeignKey(default=11112, on_delete=django.db.models.deletion.CASCADE, to='productions.productions'),
            preserve_default=False,
        ),
    ]
