# Generated by Django 3.2.5 on 2022-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0017_auto_20220221_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformity',
            name='mass_20_caps_full',
            field=models.FloatField(verbose_name='Mass of 20 filled capsules [mg]'),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_max1',
            field=models.FloatField(verbose_name='Mass of heaviest capsule [mg]'),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_max2',
            field=models.FloatField(verbose_name='Mass of second heaviest capsule [mg]'),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_max3',
            field=models.FloatField(verbose_name='Mass of third heaviest capsule [mg]'),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_min1',
            field=models.FloatField(verbose_name='Mass of lightest capsule [mg]'),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_min2',
            field=models.FloatField(verbose_name='Mass of second lightest capsule [mg]'),
        ),
        migrations.AlterField(
            model_name='uniformity',
            name='mass_min3',
            field=models.FloatField(verbose_name='Mass of third lightest capsule [mg]'),
        ),
    ]
