# Generated by Django 3.2.5 on 2022-03-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capsules', '0019_auto_20220321_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniformity',
            name='release_note',
            field=models.BooleanField(),
        ),
    ]
