# Generated by Django 3.2.5 on 2022-02-17 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_calc_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('production_lot_nr', models.CharField(max_length=32, unique=True)),
                ('production_galenical_form', models.CharField(choices=[('capsules', 'Capsules'), ('suppositories', 'Suppositories'), ('eyedrops', 'Eyedrops')], max_length=16)),
                ('production_name', models.CharField(max_length=256)),
            ],
        ),
    ]
