# Generated by Django 3.2.5 on 2022-02-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productions',
            old_name='production_calc_date',
            new_name='calc_date',
        ),
        migrations.RenameField(
            model_name='productions',
            old_name='production_galenical_form',
            new_name='galenical_form',
        ),
        migrations.RenameField(
            model_name='productions',
            old_name='production_lot_nr',
            new_name='lot_nr',
        ),
        migrations.RenameField(
            model_name='productions',
            old_name='production_name',
            new_name='name',
        ),
    ]
