# Generated by Django 3.2.5 on 2022-04-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0004_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='actual_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='target_amount',
            field=models.FloatField(null=True),
        ),
    ]
