# Generated by Django 3.2.5 on 2022-04-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0004_rename_info_substance_infos'),
        ('productions', '0005_auto_20220418_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='price_per_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('production', 'substance')},
        ),
    ]
