# Generated by Django 3.2.5 on 2022-05-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0006_auto_20220418_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
