# Generated by Django 3.2.5 on 2022-05-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0007_alter_ingredient_price_per_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productions',
            name='dose_units',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productions',
            name='dose_units_incl_excess',
            field=models.IntegerField(blank=True, default=100),
            preserve_default=False,
        ),
    ]
