# Generated by Django 3.2.5 on 2022-05-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0009_alter_productions_dose_units_incl_excess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='actual_amount',
            new_name='actual_amount_for_bulk',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='target_amount',
            new_name='target_amount_for_bulk',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='conc_per_dose_unit',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='is_filler_excipient',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='price_per_amount',
            field=models.FloatField(null=True),
        ),
    ]
