# Generated by Django 3.2.5 on 2022-05-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0010_auto_20220521_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='conc_per_dose_unit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='is_filler_excipient',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='productions',
            name='dose_units_incl_excess',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
