# Generated by Django 3.2.5 on 2022-05-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0011_auto_20220521_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='productions',
            name='calib_value_suppo_mould',
            field=models.FloatField(null=True),
        ),
    ]
