# Generated by Django 3.2.5 on 2022-05-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0012_productions_calib_value_suppo_mould'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productions',
            name='calib_value_suppo_mould',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='diff_amount_for_bulk',
            field=models.FloatField(null=True),
        ),
    ]
