# Generated by Django 3.2.5 on 2022-05-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0013_auto_20220525_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='productions',
            name='release_note',
            field=models.BooleanField(null=True),
        ),
    ]
