# Generated by Django 3.2.5 on 2022-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0015_ambvvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambvvalue',
            name='yearly_amount',
            field=models.IntegerField(choices=[('Administration route:', (('5', 'a. parenteral administration'), (4, 'b. ophthalmological administration in surgery or for traumatic injuries'), (4, 'c. inhaled administration'), (4, 'd. enteral or topical administration with requirements for sterility'), (3, 'e. enteral administration'), (1, 'f. ophthalmological administration in the uninjured eye'), (1, 'g. topical administration'))), ('19th century', (('AC', 'Agatha Christie'),))]),
        ),
    ]
