# Generated by Django 3.2.5 on 2022-05-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0016_alter_ambvvalue_yearly_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambvvalue',
            name='contract_manuf',
            field=models.IntegerField(choices=[(5, 'exclusively contract manufacture'), (4, 'mainly contract manufacture (ratio: around 2:1)'), (3, 'balanced (ratio: around 1:1)'), (2, 'mainly for own customers (ratio: around 1:2)'), (0.2, 'exclusively for own customers')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambvvalue',
            name='inherent_risk',
            field=models.IntegerField(choices=[(5, 'high risk'), (3, 'medium risk'), (1, 'low risk')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambvvalue',
            name='manuf_process',
            field=models.IntegerField(choices=[(5, 'aseptic manufacture'), (4, 'manufacture with terminal sterilisation'), (3, 'dissolving and mixing'), (2, 'diluting'), (1, 'filling of non-sterile dosage forms')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ambvvalue',
            name='roa',
            field=models.IntegerField(choices=[(5, 'parenteral administration'), (4, 'ophthalmological administration in surgery or for traumatic injuries'), (4, 'inhaled administration'), (4, 'enteral or topical administration with requirements for sterility'), (3, 'enteral administration'), (1, 'ophthalmological administration in the uninjured eye'), (1, 'topical administration')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambvvalue',
            name='yearly_amount',
            field=models.IntegerField(choices=[('a. liquid dosage forms in standard pack units or application units in litres', ((5, 'more than 2,000'), (4, '1000–2000'), (3, '500–999'), (2, '100–499'), (1, 'less than 100'))), ('b. solid dosage forms, number of units', ((5, 'more than 120,000'), (4, '60,000–120,000'), (3, '30,000–59,999'), (2, '6,000–29,999'), (1, 'less than 6000'))), ('c. semi-solid dosage forms (suppositories), number of units', ((5, 'more than 40,000'), (4, '20,000–40,000'), (3, '10,000–19,999'), (2, '2000–9999'), (1, 'less than 2000'))), ('d. semi-solid dosage forms (ointments, creams, etc.) in grams', ((5, 'more than 200,000'), (4, '100,000–200,000'), (3, '50,000–99,999'), (2, '10,000–49,999'), (1, 'less than 10,000'))), ('e. eye drops in litres', ((5, 'more than 200'), (4, '100–200'), (3, '50–99'), (2, '10–49'), (1, 'less than 10')))]),
        ),
    ]
