# Generated by Django 3.2.5 on 2022-05-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0017_auto_20220526_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambvvalue',
            name='value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ambvvalue',
            name='contract_manuf',
            field=models.FloatField(choices=[(5, 'exclusively contract manufacture'), (4, 'mainly contract manufacture (ratio: around 2:1)'), (3, 'balanced (ratio: around 1:1)'), (2, 'mainly for own customers (ratio: around 1:2)'), (0.2, 'exclusively for own customers')]),
        ),
    ]
