# Generated by Django 3.2.5 on 2022-05-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0018_auto_20220526_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambvvalue',
            name='roa',
            field=models.FloatField(choices=[(5, 'parenteral administration'), (4.000001, 'ophthalmological administration in surgery or for traumatic injuries'), (4.000002, 'inhaled administration'), (4.000003, 'enteral or topical administration with requirements for sterility'), (3, 'enteral administration'), (1.000001, 'ophthalmological administration in the uninjured eye'), (1.000002, 'topical administration')]),
        ),
    ]
