# Generated by Django 3.2.5 on 2022-07-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0020_auto_20220717_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='is_filler_excipient',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
