# Generated by Django 3.2.5 on 2022-07-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0021_alter_ingredient_is_filler_excipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='target_amount_for_bulk_pow',
            field=models.FloatField(null=True),
        ),
    ]
