# Generated by Django 3.2.5 on 2022-07-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0022_ingredient_target_amount_for_bulk_pow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='target_amount_for_bulk_pow',
            new_name='conc_per_bulk',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='required_amount_of_tabs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='required_amount_of_tabs_incl_excess',
            field=models.FloatField(null=True),
        ),
    ]
