# Generated by Django 3.2.5 on 2022-07-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0023_auto_20220717_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='weight_tabs_incl_excess',
            field=models.FloatField(null=True),
        ),
    ]
