# Generated by Django 3.2.5 on 2022-07-18 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0024_ingredient_weight_tabs_incl_excess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='required_amount_of_tabs_incl_excess',
            field=models.IntegerField(null=True),
        ),
    ]
