# Generated by Django 3.2.5 on 2022-04-07 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caps_mass_balance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capsmassbalance',
            old_name='relative_mass_balance',
            new_name='diff_mass_balance',
        ),
    ]
