# Generated by Django 3.2.5 on 2022-07-18 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps_mass_balance', '0003_capsmassbalance_conc_per_cap_actual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capsmassbalance',
            name='conc_per_cap_actual',
        ),
        migrations.AlterField(
            model_name='capsmassbalance',
            name='absolute_mass_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='capsmassbalance',
            name='calculated_mass_powder_mix',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='capsmassbalance',
            name='diff_mass_balance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='capsmassbalance',
            name='release_note',
            field=models.BooleanField(null=True),
        ),
    ]
