# Generated by Django 3.2.5 on 2022-04-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Substance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('info', models.CharField(blank=True, choices=[('nALT', 'Non-ALT substance'), ('limited', 'Limited'), ('BetmG', 'Narcotic')], max_length=32)),
                ('freezing_point_depression', models.FloatField(blank=True, null=True)),
                ('displacement_value', models.FloatField(blank=True, null=True)),
                ('price_0_001_g_ml', models.FloatField(blank=True, null=True)),
                ('price_0_01_g_ml', models.FloatField(blank=True, null=True)),
                ('price_0_1_g_ml', models.FloatField(blank=True, null=True)),
                ('price_1_g_ml', models.FloatField(blank=True, null=True)),
                ('price_10_g_ml', models.FloatField(blank=True, null=True)),
                ('price_100_g_ml', models.FloatField(blank=True, null=True)),
                ('price_500_g_ml', models.FloatField(blank=True, null=True)),
                ('price_1000_g_ml', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
