# Generated by Django 3.2.5 on 2022-04-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0002_alter_substance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substance',
            name='info',
            field=models.CharField(blank=True, choices=[('nALT', 'Non-ALT substance'), ('L', 'Limited'), ('St', 'Narcotic')], max_length=32),
        ),
    ]
