# Generated by Django 3.2.5 on 2022-04-17 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substances', '0003_alter_substance_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substance',
            old_name='info',
            new_name='infos',
        ),
    ]
