# Generated by Django 3.2.5 on 2022-04-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeDropsFreezingPointDepressionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substance', models.CharField(max_length=64)),
                ('value', models.FloatField()),
            ],
        ),
    ]
