# Generated by Django 3.2.5 on 2022-07-31 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eyedrops_prod', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EyeDropsFreezingPointDepressionValue',
        ),
    ]
